package nix

import (
	"errors"
	"fmt"
)

// ChanIsOpened tells wether the channel is opened or closed
func ChanIsOpened[T any](c chan T) bool {
	if c == nil {
		return false
	}

	open := true

	select {
	case _, open = <-c:
	default:
	}

	return open
}

// PanicToErr runs any function that returns an error in a panic-controlled
// environment and converts any panic (if any) into an error. Expecially, the
// error generated by a panic can be unwrapped to get rid of the stack trace (
// or manipulated to separate the error from the stack trace)
func PanicToErr(f func() error) error {
	errChan := make(chan error)

	go func() {
		defer func() {
			v := recover()
			if v == nil {
				errChan <- nil
			} else {
				switch err := v.(type) {
				case error:
					errChan <- fmt.Errorf("%w\n%s", err, Stack())
				default:
					errChan <- fmt.Errorf("%w\n%s", errors.New(fmt.Sprint(err)), Stack())
				}
			}
		}()
		errChan <- f()
	}()

	res := <-errChan
	close(errChan)

	return res
}
