package nix

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"
)

const (
	LogLevelInfo LogLevel = iota
	LogLevelDebug
	LogLevelWarning
	LogLevelError
	LogLevelFatal
)

// LogLevel defines the severity of a Log. See the constants
type LogLevel int

func (l LogLevel) String() string {
	switch l {
	case LogLevelInfo:
		return "   Info"
	case LogLevelDebug:
		return "  Debug"
	case LogLevelWarning:
		return "Warning"
	case LogLevelError:
		return "  Error"
	case LogLevelFatal:
		return "  Fatal"
	default:
		return "  ???  "
	}
}

// Log is the structure that can be will store any log reported
// with Logger. It keeps the error severity level (see the constants)
// the date it was created, the message associated with it (probably
// an error) and if it was generated by the user or not. It also has
// the optional field "extra" that
type Log struct {
	Level         LogLevel
	Date          time.Time
	Message       string
	Extra         string
	UserGenerated bool
}

// JSON returns the Log l in a json-encoded string in form of a
// slice of bytes
func (l Log) JSON() []byte {
	jsonL := struct {
		Level         string    `json:"level"`
		Date          time.Time `json:"date"`
		Message       string    `json:"message"`
		Extra         string    `json:"extra"`
		UserGenerated bool      `json:"userGenerated"`
	}{
		strings.TrimSpace(l.Level.String()), l.Date,
		l.Message, l.Extra,
		l.UserGenerated,
	}

	b, _ := json.Marshal(jsonL)
	return b
}

func (l Log) String() string {
	return fmt.Sprintf("[%v] - %v: %s", l.Date, l.Level, l.Message)
}

// Logger is used by the Router and can be used by the user to
// create logs that are both written to the chosen io.Writer (if any)
// and saved locally in memory, so that they can be retreived
// programmatically and used (for example to make a view in a website)
type Logger struct {
	out  io.Writer
	logs []Log
}

// NewLogger creates a new Logger with the given io.Writer out. If out
// is nil the Logger will use os.Stdout, so if you do not want to write
// any file or buffer you should open a file with os.DevNull
func newLogger(out io.Writer) *Logger {
	logger := &Logger{}
	logger.logs = make([]Log, 0)

	if out == nil {
		logger.out = os.Stdout
	} else {
		logger.out = out
	}

	return logger
}

// log first creates a new Log, appends it to the list of Logs and then prints it
// to out
func (l Logger) log(level LogLevel, userGenerated bool, message string, extra ...string) {
	log := Log{
		level, time.Now(),
		message, strings.Join(extra, ""),
		userGenerated,
	}

	l.logs = append(l.logs, log)
	fmt.Fprintln(l.out, log)
}

// Log creates a new Log with the given arguments as a user-generated log, adds it to
// the list of logs and then prints it to the io.Writer
func (l Logger) Log(level LogLevel, message string, extra ...string) {
	l.log(level, true, message, extra...)
}
